version: '3.8'

services:
  web:
    image: $DOCKER_USERNAME/friendbook:$TAG
    restart: always
    command: daphne -b 0.0.0.0 -p 8000 mysite.asgi:application
    ports:
      - "8000"  # Only exposed internally to NGINX
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - redis
      - celery
      - celery-beat

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 30s
      retries: 5

  celery:
    image: $DOCKER_USERNAME/friendbook:$TAG
    restart: always
    command: celery -A mysite worker --loglevel=info
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  celery-beat:
    image: $DOCKER_USERNAME/friendbook:$TAG
    restart: always
    command: celery -A mysite beat --loglevel=info
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/ssl  # SSL certificates folder
    depends_on:
      - web
