name: Deploy Django App to AWS EC2

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create .env File from Secrets
        run: |
          echo "DEBUG=True" > .env
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "CELERY_BROKER_URL=redis://redis:6379/0" >> .env
          echo "CELERY_RESULT_BACKEND=redis://redis:6379/0" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env

      - name: Build Docker Images
        run: docker-compose -f docker-compose.yaml build

      - name: Export EC2 Key
        run: |
          echo "${{ secrets.AWS_EC2_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Deploy Docker Compose to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_IP: ${{ secrets.AWS_EC2_IP }}
        run: |
          # Create directory if it doesn't exist and upload files
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem "$EC2_USER@$EC2_IP" 'sudo mkdir -p /home/$EC2_USER/app && sudo chown $EC2_USER:$EC2_USER /home/$EC2_USER/app'
          scp -o StrictHostKeyChecking=no -i ec2-key.pem docker-compose.yaml .env "$EC2_USER@$EC2_IP:/home/$EC2_USER/app/"

          # SSH into EC2 and deploy
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem "$EC2_USER@$EC2_IP" << 'EOF'
            cd /home/$EC2_USER/app
            docker-compose down
            docker-compose up -d --build
          EOF



      - name: Clean Up
        run: rm -f ec2-key.pem
