name: Deploy Store Hub API to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.16'

      - name: Install Dependencies
        run: npm install

      - name: Compile TS to JS
        run: npm run tsc || true

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}  # Add your region secret here
        run: |
          echo "S3_BUCKET: $S3_BUCKET"  # Debugging line
          aws s3 sync ./dist s3://$S3_BUCKET/storehub-api/ --delete --region $AWS_REGION

      - name: Deploy Files from S3 to EC2
        env:
          PEM_KEY: ${{ secrets.EC2_PEM_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          APP_DIRECTORY: "/home/${{ secrets.EC2_USER }}/storehub-api/dist"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "$PEM_KEY" > ec2-key.pem
          chmod 600 ec2-key.pem

          # Sync from S3 to EC2
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem "$EC2_USER@$EC2_HOST" "
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}; 
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}; 
          aws s3 sync s3://$S3_BUCKET/storehub-api/ $APP_DIRECTORY/ --delete --region $AWS_REGION"

          # Copy package.json only if it has changed
          scp -o StrictHostKeyChecking=no -i ec2-key.pem ./package.json "$EC2_USER@$EC2_HOST:/home/${{ secrets.EC2_USER }}/storehub-api/"
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem "$EC2_USER@$EC2_HOST" "source ~/.nvm/nvm.sh && cd /home/${{ secrets.EC2_USER }}/storehub-api && npm install"

          # Copy pm2 config and restart the app
          scp -o StrictHostKeyChecking=no -i ec2-key.pem ./ecosystem.config.cjs "$EC2_USER@$EC2_HOST:/home/${{ secrets.EC2_USER }}/storehub-api/"
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem "$EC2_USER@$EC2_HOST" "source ~/.nvm/nvm.sh && pm2 restart api"

      - name: Clean Up
        run: rm -f ec2-key.pem
